### ISSUE TITLE
Buy and configure the domain

### ISSUE THREAD

**Issue by unrealsolver** [NStar-1/beam-calculator#14]
Let's vote for the domain name in comments!
Also, I recommend [https://porkbun.com]() for registration

**Comment by unrealsolver** [comment]
beamcalc.net/app/xyz
engycalc.*
stresscalc.* # 'ssc' - bad
beamsim.net/app

**Comment by lexussuxel** [comment]
beamcalc.xyz

**Comment by lexussuxel** [comment]
![image](https://user-images.githubusercontent.com/79334896/214139353-907d85e3-bd51-497d-a2c4-7953828047e1.png)
ok.............
